image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
               -Dorg.slf4j.simpleLogger.showDateTime=true
               -Djava.awt.headless=true
               -Dmaven.repo.local=.m2/repository"

stages:
  - build

build:
  stage: build
  before_script:
  - export REVISION="$(curl http://git.patrikdufresne.com/pdsl/maven-scm-version/raw/master/version.sh | bash -)"
  - echo "REVISION=$REVISION"
  # Install SWIG
  - wget https://sourceforge.net/projects/swig/files/swig/swig-4.0.0/swig-4.0.0.tar.gz
  - tar -zxvf swig-4.0.0.tar.gz
  - cd swig-4.0.0
  - ./configure && make && make install
  - cd ..
  script:
  - apt-get update && apt-get install -y build-essential gcc-mingw-w64 mingw-w64 g++-multilib
  - mvn -B -s ./settings.xml -Drevision=${REVISION} clean install deploy
